package com.shipmate.model.admin;

public enum AdminActionType {

    SHIPMENT_CANCELLED,
    SHIPMENT_MARKED_LOST,
    SHIPMENT_STATUS_OVERRIDE,

    DRIVER_APPROVED,
    DRIVER_REJECTED,
    DRIVER_SUSPENDED,
    DRIVER_STRIKE,
    DRIVER_RESET_STRIKES,

    CLAIM_APPROVED,
    CLAIM_REJECTED,

    PAYMENT_REFUNDED,

    USER_DEACTIVATED,
    USER_ACTIVATED
}